FROM scratch

ADD "%BASE_ROOTFS_TGZ%" /
COPY "qemu-aarch64-static" "%QEMU_STATIC_GUEST_PATH%"
RUN mkdir -p /etc/pacman.d/hooks \
	&& ln -s /dev/null /etc/pacman.d/hooks/30-systemd-tmpfiles.hook

ARG REPO_URL
ENV REPO_URL $REPO_URL
