name: Build rpi4 archlinuxarm

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
        shell: bash

      - name: checkout repo
        uses: actions/checkout@v2

      - name: generate builder
        run: |
          sudo apt install qemu-user-static libarchive-tools arch-install-scripts
          sudo curl -L -o ./ArchLinuxARM-aarch64-latest.tar.gz http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
          sudo mkdir ./builder
          sudo bsdtar -xpf ./ArchLinuxARM-aarch64-latest.tar.gz -C ./builder
          sudo cp /usr/bin/qemu-aarch64-static ./builder/usr/bin/qemu-aarch64-static
          sudo cp -f ./pacman.conf ./builder/etc/pacman.conf
          sudo cp ./prepare-target.sh ./builder/prepare-target.sh
          sudo cp ./set-target.sh ./builder/set-target.sh
          sudo cp ./package-target.sh ./builder/package-target.sh
          cat ./builder/etc/pacman.conf

      - name: prepare builder
        run: |
          sudo arch-chroot ./builder qemu-aarch64-static /usr/bin/bash /prepare-target.sh

      - name: generate target
        run: |
          sudo arch-chroot ./builder qemu-aarch64-static /usr/bin/bash /set-target.sh

      - name: package target
        run: |
          sudo arch-chroot ./builder qemu-aarch64-static /usr/bin/bash /package-target.sh

      - name: generate img file
        run: |
          mkdir ./release
          sudo mv ./builder/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz
          sudo dd if=/dev/zero of=ArchLinuxARM-rpi-4-aarch64-latest.img bs=4000 count=1000000
          echo LOOP0=$(sudo losetup --partscan --show --find ArchLinuxARM-rpi-4-aarch64-latest.img) >> $GITHUB_ENV
          sudo parted -s ${{ env.LOOP0 }} mklabel msdos
          sudo parted -s ${{ env.LOOP0 }} mkpart primary fat32 2048s 411647s
          sudo parted -s ${{ env.LOOP0 }} mkpart primary ext4 411648s 100%
          sudo losetup -d ${{ env.LOOP0 }}
          echo LOOP1=$(sudo losetup --partscan --show --find ArchLinuxARM-rpi-4-aarch64-latest.img) >> $GITHUB_ENV
          echo ${{ env.LOOP1 }}
          sudo mkfs.vfat -F 32 ${{ env.LOOP1 }}p1
          sudo mkfs.ext4 ${{ env.LOOP1 }}p2
          sudo mkdir -p image/root
          sudo mount ${{ env.LOOP1 }}p2 image/root
          sudo mkdir -p image/root/boot
          sudo mount ${{ env.LOOP1 }}p1 image/root/boot
          sudo bsdtar -xpf ArchLinuxARM-rpi-4-aarch64-latest.tar.gz -C image/root
          sudo sync
          sudo umount -R image/root
          sudo losetup -d ${{ env.LOOP1 }}
          sudo zip ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip ArchLinuxARM-rpi-4-aarch64-latest.img

      - name: generate sha256 hash
        run: |
          sha256sum ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz > ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
          sha256sum ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip > ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip.sha256sum

      - name: delete old release
        uses: ame-yu/action-delete-latest-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload ArchLinuxARM-rpi-4-aarch64-latest.tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz
          asset_name: ArchLinuxARM-rpi-4-aarch64-latest.tar.gz
          asset_content_type: application/gzip

      - name: Upload ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
          asset_name: ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
          asset_content_type: text/plain

      - name: Upload ArchLinuxARM-rpi-4-aarch64-latest.img.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip
          asset_name: ArchLinuxARM-rpi-4-aarch64-latest.img.zip
          asset_content_type: application/gzip

      - name: Upload ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip.sha256sum
          asset_name: ArchLinuxARM-rpi-4-aarch64-latest.img.zip.sha256sum
          asset_content_type: text/plain
