name: Build rpi4 archlinuxarm

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
        shell: bash

      - name: checkout repo
        uses: actions/checkout@v2

      - name: generate builder
        run: |
          sudo apt install qemu-user-static libarchive-tools arch-install-scripts
          sudo curl -L -o ./ArchLinuxARM-aarch64-latest.tar.gz http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
          sudo mkdir ./builder
          sudo bsdtar -xpf ./ArchLinuxARM-aarch64-latest.tar.gz -C ./builder
          sudo cp /usr/bin/qemu-aarch64-static ./builder/usr/bin/qemu-aarch64-static
          sudo cp -f ./pacman.conf ./builder/etc/pacman.conf
          cat ./builder/etc/pacman.conf
          BUILDER_ENV='sudo arch-chroot ./builder qemu-aarch64-static /usr/bin'
          TARGET_ENV='$BUILDER_ENV/bash arch-chroot /mnt'
          $BUILDER_ENV/pacman -Sy --ask=4 arch-install-scripts

      - name: generate img file
        run: |
          $BUILDER_ENV/dd if=/dev/zero of=ArchLinuxARM-rpi-4-aarch64-latest.img bs=4000 count=1000000
          $BUILDER_ENV/losetup --partscan /dev/loop10 ArchLinuxARM-rpi-4-aarch64-latest.img
          $BUILDER_ENV/parted -s /dev/loop10 mklabel msdos
          $BUILDER_ENV/parted -s /dev/loop10 mkpart primary fat32 2048s 411647s
          $BUILDER_ENV/parted -s /dev/loop10 mkpart primary ext4 411648s 100%
          $BUILDER_ENV/losetup -d /dev/loop10
          $BUILDER_ENV/losetup --partscan /dev/loop10 ArchLinuxARM-rpi-4-aarch64-latest.img
          $BUILDER_ENV/mkfs.vfat -F 32 /dev/loop10p1
          $BUILDER_ENV/mkfs.ext4 /dev/loop10p2
          $BUILDER_ENV/mkdir -p /mnt/boot
          $BUILDER_ENV/mount /dev/loop10p2 /mnt
          $BUILDER_ENV/mkdir -p /mnt/boot
          $BUILDER_ENV/mount /dev/loop10p1 /mnt/boot

      - name: generate target
        run: |
          $BUILDER_ENV/bash pacstrap -cGM /mnt base linux-raspberrypi4 crda dhcpcd dialog haveged nano net-tools netctl openssh raspberrypi-bootloader raspberrypi-bootloader-x vi which wireless_tools wpa_supplicant
          $BUILDER_ENV/rm /mnt/etc/resolv.conf
          $TARGET_ENV/systemctl enable sshd systemd-networkd systemd-resolved systemd-timesyncd haveged
          $TARGET_ENV/echo -e '[Match]\nName=en*\n\n[Network]\nDHCP=yes\nDNSSEC=no'>/etc/systemd/network/en.network
          $TARGET_ENV/echo -e '[Match]\nName=eth*\n\n[Network]\nDHCP=yes\nDNSSEC=no'>/etc/systemd/network/eth.network
          $TARGET_ENV/echo '/dev/mmcblk0p1  /boot   vfat    defaults        0       0'>>/etc/fstab
          $TARGET_ENV/echo 'alarm'>/etc/hostname
          $TARGET_ENV/echo 'LANG=C'>/etc/locale.conf
          $TARGET_ENV/echo "root:root" | chpasswd
          $TARGET_ENV/useradd -d /home/alarm -m -U -p `openssl passwd -6 alarm` alarm
          $TARGET_ENV/ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf

      - name: package target
        run: |
          $BUILDER_ENV/rm -rf /mnt/etc/*- /mnt/root/.bash_history /mnt/root/.gnupg /mnt/var/log/* /mnt/var/lib/systemd/* 
          $BUILDER_ENV/bsdtar -czpf /ArchLinuxARM-rpi-4-aarch64-latest.tar.gz -C /mnt/ . --exclude lost+found
          $BUILDER_ENV/losetup -d /dev/loop10
          $BUILDER_ENV/zip ArchLinuxARM-rpi-4-aarch64-latest.img.zip ArchLinuxARM-rpi-4-aarch64-latest.img

      - name: generate release
        run: |
          mkdir ./release
          sudo mv ./builder/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz
          sudo mv ./builder/ArchLinuxARM-rpi-4-aarch64-latest.img.zip ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip
          sha256sum ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz > ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
          sha256sum ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip > ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip.sha256sum

      - name: delete old release
        uses: ame-yu/action-delete-latest-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload ArchLinuxARM-rpi-4-aarch64-latest.tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz
          asset_name: ArchLinuxARM-rpi-4-aarch64-latest.tar.gz
          asset_content_type: application/gzip

      - name: Upload ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
          asset_name: ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
          asset_content_type: text/plain

      - name: Upload ArchLinuxARM-rpi-4-aarch64-latest.img.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip
          asset_name: ArchLinuxARM-rpi-4-aarch64-latest.img.zip
          asset_content_type: application/gzip

      - name: Upload ArchLinuxARM-rpi-4-aarch64-latest.tar.gz.sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/ArchLinuxARM-rpi-4-aarch64-latest.img.zip.sha256sum
          asset_name: ArchLinuxARM-rpi-4-aarch64-latest.img.zip.sha256sum
          asset_content_type: text/plain
